function updateDoc
% updateDoc - parses all the m-files and creates the html documentaion 
% in the doc folder. 
%
% the function reads all the source code and create the documentation from existings
% comments. To create good documentation mostly follow the matlab
% commenting rules for functions. Only exception is the object properties
% that are extracted from the class get/set method. Write the properties
% description as a long line in the get method and any comments about input
% values in the set properties.

%% add m2html to the path if necessary
if ~exist('m2html.m','file')
    addpath([pwd filesep 'ThirdParty' filesep 'utilities' filesep 'm2html']);
    addpath([pwd filesep 'ThirdParty' filesep 'utilities']);
end

%% create the html docs
m2html('mFiles','.',...
       'recursive','on',...
       'htmlDir','doc',...
       'todo','on',...
       'source','off',...
       'graph','on',...
       'index','menu',...
       'template','frame',...
       'global','on',...
       'ignoreddir', {'.svn','cvs','ThirdParty','oldCode',...
                      'private','ImageAnalysis','html',...
                      'Users'});





