function updateTiffMetaData( md )
%UPDATETIFFMETADATA replaces the metadata in a Tiff file

%THE ONLY WAY I COULD FIND TO UPDATE A METADATA TIFF IF TO REWRITE THE
%IMAGE... MUST BE A BETTER WAY, BUT UNTIL THAN, USE THIS FUNCTION
%SELDOMLY...


